pipeline {
    agent any
    
    environment {
        // 본인의 DockerHub Username을 넣으세요
        DOCKERHUB_USERNAME = '1pro'
        // 본인의 GitHub URL을 넣으세요
        GITHUB_URL = 'https://github.com/k8s-1pro/kubernetes-anotherclass-sprint2.git'

        // 실습 넘버링 - (수정x)
        CLASS_NUM = '2212'
    }
    
    stages {
        stage('Source Checkout') {
            steps {
                // 소스코드를 가져올 Github 주소
                git branch: 'main', url: 'https://github.com/k8s-1pro/kubernetes-anotherclass-api-tester.git'
            }
        }	
        stage('Source Build') {
            steps {
                // 755권한 필요 (윈도우에서 Git으로 소스 업로드시 권한은 644)
                sh "chmod +x ./gradlew"
                sh "./gradlew clean build"
            }
        }
		
        stage('Container Checkout') {
            steps {
			
				checkout scmGit(branches: [[name: '*/main']], 
								extensions: [[$class: 'SparseCheckoutPaths', 
								              sparseCheckoutPaths: [[path: "/${CLASS_NUM}"]]]],
								userRemoteConfigs: [[url: "${GITHUB_URL}"]])
            }
        }		
		
        stage('Container Build') {
            steps {                
				// jar 파일 복사
                sh "cp ./build/libs/app-0.0.1-SNAPSHOT.jar ./${CLASS_NUM}/build/docker/app-0.0.1-SNAPSHOT.jar"
				
				// 도커 빌드
				sh "docker build -t ${DOCKERHUB_USERNAME}/api-tester:v1.0.0 ./${CLASS_NUM}/build/docker"
            }
        }
		
        stage('Container Push') {
            steps {                
				// DockerHub로 이미지 업로드
				echo "docker push ${DOCKERHUB_USERNAME}/api-tester:v1.0.0"
            }
        }
		
        stage('K8S Deploy') {
            steps {
				// K8S 배포 
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/namespace.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/pv.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/pvc.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/configmap.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/secret.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/service.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/hpa.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/deployment.yaml"
            }
        }
    }
}