pipeline {
    agent any



    environment {
        // 본인의 username으로 하실 분은 수정해주세요.
        DOCKERHUB_USERNAME = '1pro'
        GITHUB_URL = 'https://github.com/k8s-1pro/kubernetes-anotherclass-sprint2.git'

        // 태그 생성
        APP_VERSION = '1.0.1'
        BUILD_DATE = sh(script: "echo `date +%y%m%d.%d%H%M`", returnStdout: true).trim()
        TAG = "${APP_VERSION}-" + "${BUILD_DATE}"

        // 실습 넘버링
        CLASS_NUM = '2231'
    }
    
    stages {
        stage('깃허브 태그 업데이트') {
            steps {
                sh '''
                git config --global user.email "k8s-1pro@github.com"
                git config --global user.name "k8s-1pro"
                sed -i "s%${DOCKERHUB_USERNAME}/api-tester:.*%${DOCKERHUB_USERNAME}/api-tester:${TAG}%" ${CLASS_NUM}/deploy/k8s/deployment.yaml
                git add ${CLASS_NUM}/deploy/k8s/deployment.yaml
                git commit -m "Api Tester Tag Update by Jenkins-$BUILD_NUMBER "
                git push origin +main
                '''
            }
        }
    }
}