pipeline {
    agent any
    
    environment {
        GITHUB_URL = 'https://github.com/k8s-1pro/kubernetes-anotherclass-sprint2.git'
        // 실습 넘버링
        CLASS_NUM = '2214'
    }

    stages {

        stage('릴리즈파일 체크아웃') {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                        extensions: [[$class: 'SparseCheckoutPaths',
                                      sparseCheckoutPaths: [[path: "/${CLASS_NUM}"]]]],
                        userRemoteConfigs: [[url: "${GITHUB_URL}"]])
            }
        }

        stage('쿠버네티스 Blue배포') {
            steps {
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/namespace.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/configmap.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/secret.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/service.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/deployment.yaml"
            }
        }

        stage('자동배포 시작') {
            steps {
                input message: '자동배포 시작', ok: "Yes"
            }
        }

        stage('쿠버네티스 Green배포') {
            steps {
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/namespace.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/configmap.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/secret.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/service.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/deployment.yaml"
            }
        }

        stage('배포 확인') {
            steps {
                script {
                    def IS_RESULT
                    while (IS_RESULT != "true true"){
                        IS_RESULT = sh(returnStdout: true, encoding: 'UTF-8', script: "kubectl get -n anotherclass-212 pods --selector=version='1.0.0' -o jsonpath='{.items[*].status.containerStatuses[*].ready}'")
                        echo "${IS_RESULT}"
                    }
                }
            }
        }

        stage('Green 전환 확인') {
            steps {
                sh "kubectl patch -n anotherclass-221 svc api-tester-2214-blue -p '{\"spec\": {\"selector\": {\"version\": \"2.0.0\", \"instance\": \"api-tester-2214-green\"}}}'"
            }
        }

        stage('Blue 삭제') {
            steps {
                input message: 'Green 전환?', ok: "Yes", parameters: [booleanParam(defaultValue: true, name: 'IS_SWITCHED')]

                sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/blue/namespace.yaml"
                sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/blue/configmap.yaml"
                sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/blue/secret.yaml"
                sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/blue/deployment.yaml"
                sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/green/service.yaml"
            }
        }
    }
}