pipeline {
    agent any
    
    environment {
        GITHUB_URL = 'https://github.com/k8s-1pro/kubernetes-anotherclass-sprint2.git'

        // 실습 넘버링
        CLASS_NUM = '2213'
    }

    stages {
        stage('릴리즈파일 체크아웃') {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                        extensions: [[$class: 'SparseCheckoutPaths',
                                      sparseCheckoutPaths: [[path: "/${CLASS_NUM}"]]]],
                        userRemoteConfigs: [[url: "${GITHUB_URL}"]])
            }
        }

        stage('쿠버네티스 Blue배포') {
            steps {
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/namespace.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/configmap.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/secret.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/service.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/blue/deployment.yaml"
            }
        }

        stage('쿠버네티스 Green배포') {
            steps {
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/namespace.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/configmap.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/secret.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/service.yaml"
				sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/green/deployment.yaml"
            }
        }

        stage('배포 확인') {
            steps {
                // 10초 대기
                sh "sleep 10"

				// Blue 확인
                sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/blue/namespace.yaml"
				sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/blue/configmap.yaml"
				sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/blue/secret.yaml"
				sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/blue/service.yaml"
				sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/blue/deployment.yaml"

				// Green 확인
                sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/green/namespace.yaml"
				sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/green/configmap.yaml"
				sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/green/secret.yaml"
				sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/green/service.yaml"
				sh "kubectl get -f ./${CLASS_NUM}/deploy/k8s/green/deployment.yaml"
            }
        }

        stage('Green 전환 확인') {
            steps {
                input message: 'Green 전환?', ok: "Yes", parameters: [booleanParam(defaultValue: true, name: 'IS_SWITCHED')]

                script {
                    if (${IS_SWITCHED}) {
                        sh "kubectl patch -n anotherclass-221 svc api-tester-2213-blue -p '{\"spec\": {\"selector\": {\"version\": \"2.0.0\", \"instance\": \"api-tester-2213-green\"}}}'"
                    }
                }
            }
        }

        stage('Blue 삭제 확인') {
            steps {
                input message: 'Blue 삭제?', ok: "Yes", parameters: [booleanParam(defaultValue: true, name: 'IS_DELETED')]

                script {
                    if (${IS_DELETED}) {
                        sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/blue/namespace.yaml"
                        sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/blue/configmap.yaml"
                        sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/blue/secret.yaml"
                        sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/blue/deployment.yaml"
                        sh "kubectl delete -f ./${CLASS_NUM}/deploy/k8s/green/service.yaml"
                    }
                }
            }
        }
    }
}